services:
  django:
    build: .
    restart: always
    ports:
      - 8001:8000
    env_file: "./.env"
    environment:
      - DEFAULT_DB_HOST=host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./dumps:/app/dumps
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --workers 12 --reload --time 300
#    command: python manage.py runserver 0.0.0.0:8000