services:
  django:
    build: .
    ports:
      - 8001:8001
    env_file: "./.env"
    environment:
      - DEFAULT_DB_HOST=host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./dumps:/app/dumps
