# Generated by Django 4.2.3 on 2024-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentsyst_id', models.IntegerField()),
                ('vendor', models.CharField(max_length=255)),
            ],
        ),
    ]
