# Generated by Django 4.2.3 on 2023-09-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rentsyst id')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
                ('mark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mark')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Group')),
            ],
        ),
    ]
