# Generated by Django 4.2.3 on 2023-09-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Priority'),
        ),
    ]
