# Generated by Django 4.2.3 on 2023-09-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options_alter_product_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-priority']},
        ),
    ]
