# Generated by Django 4.2.3 on 2023-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_currency_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail'),
        ),
    ]
