# Generated by Django 4.2.3 on 2024-06-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='products/original/%Y/%m/%d', verbose_name='Original image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/%Y/%m/%d', verbose_name='Thumbnail image'),
        ),
    ]
