# Generated by Django 4.2.3 on 2024-06-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_image_original_product_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_small',
        ),
    ]
