# Generated by Django 5.1.1 on 2024-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='product_image/original/%Y/%m/%d', verbose_name='Original'),
        ),
    ]
