# Generated by Django 5.1.1 on 2024-09-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productimage_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Body type (sedan, hatchback)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color code'),
        ),
        migrations.AddField(
            model_name='product',
            name='consumption',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Consumption'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fuel'),
        ),
        migrations.AddField(
            model_name='product',
            name='large_bags',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Large bags'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_doors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number doors'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number seats'),
        ),
        migrations.AddField(
            model_name='product',
            name='odometer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Odometer'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type (car, motorcycle, truck)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_engine',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume engine'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_tank',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Volume tank'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
