# Generated by Django 5.1.1 on 2024-09-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_original',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_thumbnail',
        ),
    ]
