# Generated by Django 5.1.1 on 2024-09-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, null=True, upload_to='product_image/original/%Y/%m/%d', verbose_name='Original'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('days_min', models.SmallIntegerField(verbose_name='Days min')),
                ('days_max', models.SmallIntegerField(blank=True, null=True, verbose_name='Days max')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product')),
            ],
        ),
    ]
