# Generated by Django 5.1.1 on 2024-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_productimage_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='days_max',
            field=models.SmallIntegerField(verbose_name='Days max'),
        ),
    ]
