# Generated by Django 5.1.1 on 2024-09-17 12:23

from django.db import migrations


def migrate_price(apps, schema_editor):
    """
    Migration that copies price from product table to price table
    """
    Product = apps.get_model('product', 'Product')
    Price = apps.get_model('product', 'Price')
    for product in Product.objects.all():
        if not product.price:
            continue
        price = Price.objects.update_or_create(
            product=product,
            price=product.price,
            days_min=1,
            days_max=3
        )


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_price_days_max'),
    ]

    operations = [
        migrations.RunPython(migrate_price)
    ]
