# Generated by Django 5.1.1 on 2024-09-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20240917_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
